name: Scheduled Sync

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0 点执行
  workflow_dispatch:    # 允许手动触发

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 注意：下面这里的参数名已经修改
          upstream_repo_access_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: dev-deer/deer-flow  # 这里请确保填写原作者的仓库名
          target_sync_branch: main
          upstream_sync_branch: main
          test_mode: false
